My_First_Project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("first_app.urls")),


]

first_app/urls.py
from django.conf.urls import  url
from django.urls import path
from . import views

app_name="first_app"

urlpatterns = [

    path("",views.index,name="index"),
    path("add_student/",views.add_student,name="add_student"),
    path("add_subject/",views.add_subject,name="add_subject"),
    path("student_detail/<int:id>",views.student_detail,name="student_detail"),
    path("edit_student/<int:id>",views.edit_info_student,name="edit"),
    path("edit_subject/<int:id>",views.edit_info_subject,name="edit"),
    path("delete_sub/<int:id>",views.delete_subject,name="delete"),
    path("delete_stu/<int:id>",views.delete_student,name="delete"),


]

first_app/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    cgpa = models.DecimalField(max_digits=4,decimal_places=2)

    def __str__(self):
        return self.first_name+" "+self.last_name

class Subject(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    code = models.IntegerField()
    difficulty = (
    (1,"Very Easy"),
    (2,"Easy"),
    (3,"Medium"),
    (4,"Hard"),
    (4,"DROPPP!!!!!"),
    )
    difficulty_level = models.IntegerField(choices=difficulty)

    def __str__(self):
        return self.name+" Difficulty Level: "+str(self.difficulty_level)

first_app/forms.py
from django import forms
from .models import Student,Subject

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields= "__all__"


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = "__all__"

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Student,Subject
from first_app import forms
# Create your views here.


def index(request):
    all_students = Student.objects.order_by("-cgpa")
    diction = {"all_students":all_students}
    return render(request,"first_app/index.html",context=diction)

def add_student(request):
    student_form = forms.StudentForm()
    diction = {"title":"Enlist_Student","student_form":student_form}

    if request.method=="POST":
        student_form = forms.StudentForm(request.POST)
        if student_form.is_valid():
            student_form.save()
            return index(request)

    return render(request,"first_app/add_student.html",context=diction)

def add_subject(request):
    subject_form = forms.SubjectForm()
    diction = {"title":"Add Subject","subject_form":subject_form}

    if request.method == "POST":
        subject_form = forms.SubjectForm(request.POST)
        if subject_form.is_valid():
            subject_form.save()
            return index(request)
    return render(request,"first_app/add_subject.html",context=diction)

def student_detail(request,id):
    get_student = Student.objects.get(pk=id)
    get_subject = Subject.objects.filter(student=id).order_by('-difficulty_level')
    diction = {"title":"Student Info","student_info":get_student,"subjects":get_subject}
    return render(request,"first_app/student_info.html",context=diction)

def edit_info_student(request,id):
    get_student = Student.objects.get(pk=id)
    student_form = forms.StudentForm(instance=get_student)
    if request.method=="POST":
        student_form = forms.StudentForm(request.POST,instance=get_student)
        if student_form.is_valid():
            student_form.save()
            return student_detail(request,id)

    diction = {'student_form':student_form,"title":"Edit Info","student_edit":True}
    return render(request,"first_app/edit_page.html",context=diction)

def edit_info_subject(request,id):
    get_subject = Subject.objects.get(pk=id)
    subject_form = forms.SubjectForm(instance=get_subject)
    diction ={"updated":False}
    if request.method=="POST":
        subject_form = forms.SubjectForm(request.POST,instance=get_subject)
        if subject_form.is_valid():
            subject_form.save()
            diction.update({"updated":True})
    diction.update({"title":"Edit"})
    diction.update({"subject_form":subject_form})
    diction.update({"id":id})
    return render(request,"first_app/edit_page.html",context=diction)

def delete_subject(request,id):
    delete_subject = Subject.objects.get(pk=id).delete()
    diction = {"message":"Deleted successfully"}
    return render(request,"first_app/delete_info.html",context=diction)

def delete_student(request,id):
    delete_student = Student.objects.get(pk=id).delete()
    diction = {"message":"Deleted successfully"}
    return render(request,"first_app/delete_info.html",context=diction)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>{% block title %} Home {% endblock %}</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<body>

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'first_app:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:add_student' %}">Add Student</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:add_subject' %}">Add Subject</a>
      </li>
    </ul>
  </nav>

  <div class="container mt-2">
    {% block content %}
    {% endblock %}
  </div>

</body>

</html>

templates/first_app/add_student.html
{% extends "base.html" %}
{% block title %} Adding Student {% endblock %}
{% block content %}
<h1>Student Form</h1>
<form method="POST">
  {{ student_form.as_p }}
  {% csrf_token %}
  <input type="submit"  value="Add" class="btn btn-primary btn-lg">

</form>
{% endblock %}

templates/first_app/add_subject.html
{% extends "base.html" %}
{% block title %} Adding Subject{% endblock %}
{% block content %}
<h1>Subject Form</h1>
<form method="POST">

  {{ subject_form.as_p }}
  {% csrf_token %}
  <input type="submit"  value="Add" class="btn btn-primary btn-lg">

</form>
{% endblock %}

templates/first_app/delete_info.html
{% extends "base.html" %}
{% block title %} Delete {% endblock %}
{% block content %}

{% if message %}

<div class="alert alert-danger">{{ message }}

</div>
{% else %}
{% endif %}

{% endblock %}

templates/first_app/edit_page.html
{% extends 'base.html' %}
{% block title %} EDIT INFO {% endblock %}
{% block content %}

<h4><i>Edit Information</i></h4>
{% if student_edit %}

<form method="POST">
  {{ student_form.as_p }}
  {% csrf_token %}
  <input type="submit" value="Update" class="btn btn-primary btn-lg">

</form>

{% else %}
{% if updated %}
<div class="alert alert-success">Successfully Updated!!!!

</div>
{% else %}
<form method="POST">
  {{ subject_form.as_p }}
  {% csrf_token %}
  <input type="submit" value="Update" class="btn btn-primary btn-lg">
  <a href="{% url 'first_app:delete' id=id %}" class="btn btn-danger btn-lg" onclick="return confirm('Do you really want to delete that?')">Delete</a>

</form>
{% endif %}

{% endif %}

{% endblock %}

templates/first_app/index.html
{% extends "base.html" %}
{% block content %}
<h1 class="text-center">Welcome To Student List</h1>
{% if all_students %}
<ul>
  {% for student in all_students %}
  <li> <a href="{% url 'first_app:student_detail' id=student.pk %}">{{ student.first_name }} {{ student.last_name }}</a> </li>
  {% endfor %}
</ul>
{% else %}
<h2>No Students Added</h2>
{% endif %}
{% endblock %}

templates/first_app/student_info.html
{% extends 'base.html' %}
{% block title %} Student Detail {% endblock %}
{% block content %}

<h4>Name: <b>{{ student_info.first_name }} {{ student_info.last_name }} </b></h4>
<h6>Cgpa: {{ student_info.cgpa }}</h6>
<a href="{% url 'first_app:edit' id=student_info.pk %}" class="btn btn-primary btn-lg">Edit</a>
<a href="{% url 'first_app:delete' id=student_info.id %}" class="btn btn-danger btn-lg" onclick="return confirm('Do you really want to delete that?')">Delete</a>
<br>
<hr>
<h3>Taken Courses:</h3>
{% if subjects %}
<table class="table table-striped table-bordered">
  <tr>
    <th>Name</th>
    <th>Course Code</th>
    <th>Difficulty</th>
  </tr>
  <tr>
    {% for subjects in subjects %}
    <td> <a href="{% url 'first_app:edit' id=subjects.pk %}">{{ subjects.name }} </a> </td>
    <td>{{ subjects.code }}</td>
    <td>{{ subjects.difficulty_level }}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
<h3>No Courses Taken</h3>
{% endif %}
{% endblock %}